### PR TITLE
Switch to using the npm published version of the client fh-js-sdk

### PR DESCRIPTION
**Pull request by nialldonnellyfh**
# Motivation

The conventional way to consume the fh-js-sdk is to now use NPM. This should remove the need to have the large `feedhenry.js` file in the project.

I will also prevent having to copy-paste the build fh-js-sdk files into the project.

# Changes

- Deleted the `feedhenry.js` file.
- Switched the require statement to reference the fh-js-sdk node module.

### CODE REVIEW

**Comment by paolobueno** [comment]
browserify \o/

**Review by paolobueno — APPROVED** [review]
We need to merge these changes to `development` so we can rebase the feature branches too.

**Review by wtrocki — APPROVED** [review]
Reviewed and verified using local setup. Let's merge his to development

**Comment by wtrocki** [comment]
@paolobueno Rebased your changes. Please merge this to master once you are happy with it!

**Comment by paolobueno** [comment]
@wtrocki it seems the @nialldonnellyfh's changes from 54bba89 have already landed on master through  @witmicko's 366ac34b somehow.

If you look at the current comparison there's just an extra comment, I think we can actually close this one.

**Pull request closed without merging**
