### PR TITLE
RAINCATCH-485: Data Reset Feature Branch

### PR DESCRIPTION
**Pull request by nialldonnellyfh**
Feature branch for the data reset functionality.

### CODE REVIEW

**Comment by paolobueno** [comment]
Change base branch so we can release this along with the rest of the issues in the Epic.

**Comment by wtrocki** [comment]
@paolobueno @nialldonnellyfh Should we merge that?

**Comment by paolobueno** [comment]
Going to go ahead and merge this. Issue has been verified along with the data-manipulation ones from the same epic and is a for shipping the feature.

**Comment by wtrocki** [comment]
@paolobueno Not sure if we should get that into development branch?

**Comment by paolobueno** [comment]
@wtrocki Yes, that's what I thought too, the feature branch is already merged, so this can go straight to development

**Pull request merged**
